[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
async-trait = { version = "0.1.83" }
bytes = { version = "1.1" }
chrono = { version = "0.4.38, <0.4.40", features = ["serde"] }
itertools = { version = "0.14.0" }
pbjson = { version = "0.7" }
pbjson-types = { version = "0.7" }
prost = { version = "0.13.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
strum = { version = "0.27", features = ["derive"] }
thiserror = { version = "2" }
tracing = { version = "0.1", features = ["log"] }
url = { version = "2.5.2", features = [
    "serde",
    "std",
], default-features = false }
uuid = { version = "1", features = ["serde"] }
