name: chores

on:
  pull_request:
env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DEFAULT_FEATURES: "azure,datafusion,s3,gcs,glue,hdfs"

    steps:
      - uses: actions/checkout@v5

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
          cache: true

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: build and lint with clippy
        run: cargo clippy --all-features --tests

      - name: Run Machete to check for unused dependencies
        uses: bnjbvr/cargo-machete@v0.9.1

  typos:
    name: spell-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check spelling
        uses: crate-ci/typos@v1
