name: dev

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    name: validate-pr
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: conventional-commits
        uses: ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
